apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-jxjw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/bmorley-tenant/my-app/devfile-sample-python-basic-jxjw@sha256:6ee53c227424a4ab42766dd6d5902f4d27aad0c776f0e2ebe307174de3f3e463
        name: my-python
        resources: {}
status: {}
