apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-jxjw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-jxjw
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-python-basic-jxjw
  namespace: bmorley-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-jxjw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-jxjw
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/bmorley-tenant/my-app/devfile-sample-python-basic-jxjw@sha256:6ee53c227424a4ab42766dd6d5902f4d27aad0c776f0e2ebe307174de3f3e463
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
